spring:
  datasource:
    hikari:
      username: #your database username
      password: #your database password
      auto-commit: off
      connection-test-query: #your connection test query
      validation-timeout: #your validation timeout
      minimum-idle: #your minimum idle
      maximum-pool-size: #your maximum pool size
      connection-timeout: #your connection timeout
    driver-class-name: #your driver class name
    url: #your database url
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: # your oauth2 token introspection uri
          client-id: # your oauth2 client id
          client-secret: # your oauth2 client secret